### ISSUE TITLE
New Node Release?

### ISSUE THREAD

**Issue by peternewman** [SmolSoftBoi/vestel-tv-api#69]
I see there's a typo in the Readme on npm ( https://www.npmjs.com/package/vestel-tv-api ), which presumably means that all these changes aren't in the npm release?:
https://github.com/SmolSoftBoi/vestel-tv-api/compare/db2e84bb15cd593a19f4eb1e6517453583395b99...master

**Comment by SmolSoftBoi** [comment]
Hey @peternewman,

Thanks for pointing out the typo in the Readme on npm. I've just updated the npm package to ensure all the recent changes, including the typo fix, are now live in the latest release. You can check out the updated package at [vestel-tv-api on npm](https://www.npmjs.com/package/vestel-tv-api).

If you spot any more issues or have suggestions, feel free to let me know!

Cheers,
Kristian

**Comment by peternewman** [comment]
Thanks for that @SmolSoftBoi, however for some reason I still only see v0.0.1 from four years ago on npm:
https://www.npmjs.com/package/vestel-tv-api?activeTab=versions

I'll open some other suggestions if you're feeling bored! :laughing:
